export default function MdxLayout({ children }: { children: React.ReactNode }) {
  // We apply the 'prose' class here to style the raw HTML generated by MDX
  return <article className="prose">{children}</article>;
}